# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Instalando Sdk 5.0'
  inputs:
    packageType: 'sdk'
    version: '5.0.102'

- task: DotNetCoreCLI@2
  displayName: 'Restaurando Dependências'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    noCache: true

- task: DotNetCoreCLI@2
  displayName: 'Rodando o Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '-c $(buildConfiguration) --no-restore'
  
- task: DotNetCoreCLI@2
  displayName: 'Rodando Testes Automatizados'
  inputs:
    command: 'test'
    projects: '**/Optsol.Components.Test.*/*.csproj'
    arguments: '-c $(buildConfiguration) --no-restore --no-build --collect "Code coverage"'

- task: DotNetCoreCLI@2
  displayName: 'Criando Pacote Nuget'
  inputs:
    command: 'custom'
    projects: |
      **/src/*Components*/*.csproj
      !**/*.Test.*/*.csproj
      !**/playground/
    custom: 'pack'
    arguments: '--no-restore --no-build'